[tool.poetry]
name = "bitcoin-lite"
version = "0.1.5"
description = "A lightweight Bitcoin transaction system using Cython"
authors = ["Dany Mukesha <danymukesha@gmail.com>"]
homepage = "https://github.com/danymukesha/bitcoin-lite"
readme = "README.md"
keywords = ["bitcoin-lite", "blockchain", "danymukesha"]

[tool.poetry.dependencies]
python = "^3.10"
Cython = "^3.0.11"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
