[tool.poetry]
name = "mysql-table-model"
version = "0.1.3"
description = "CYG 本地MES数据表模型"
authors = ["LiuWei <183074632@qq.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
sqlalchemy = "^2.0.36"
mysql-api = "^0.1.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
