[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "pycodemap"
version = "1.0.6"
description = "A CLI tool for extracting and outlining the structure of Python code."
readme = "README.md"
license = {text = "MIT"}
authors = [{name = "Artyom Prokhorov"}]
requires-python = ">=3.6"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
Repository = "https://github.com/your_username/PyCodeMap"

[project.scripts]
pycodemap = "pycodemap.__main__:run"

[tool.isort]
profile = "black"


