[build-system]
requires = ["setuptools>=61.0", "versioningit"]
build-backend = "setuptools.build_meta"


# ----------------------------------------- setuptools -------------------------------------------
[tool.setuptools]
include-package-data = true
zip-safe = false

[tool.setuptools.packages.find]
where = ["src"]
namespaces = true


# ----------------------------------------- Project Metadata -------------------------------------
[project]
version = "0.0.0.dev66"
name = "Pdep"
requires-python = ">=3.10"
dependencies = [
    "requirements-parser >= 0.11.0",
    "packaging",
    "LoggerMan == 0.0.0.dev78",
    "MDit == 0.0.0.dev48",
    "PyShellMan == 0.0.0.dev38",
    "PySyntax == 0.0.0.dev5",
]
