[tool.poetry]
name = "ai3-workers"
version = "0.1.3"
description = "Utilities and standard configurations for creating Streamlit workers in the AIAIAI ecosystem"
authors = ["Martijn Schouten <martijn@aiaiai.eu>"]
readme = "README.md"
packages = [{include = "ai3_workers"}]
license = "CC-BY-NC-4.0"
homepage = "https://hub.nucleoo.com/aiaiai/ai3-workers"
repository = "https://hub.nucleoo.com/aiaiai/ai3-workers"
keywords = ["streamlit", "aiaiai", "workers", "utilities"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "License :: Other/Proprietary License",
]

[tool.poetry.dependencies]
python = "^3.11"
streamlit = "^1.40.2"
typing-extensions = "^4.12.2"

[tool.poetry.group.dev.dependencies]
pytest = "^8.3.4"
black = "^24.10.0"
isort = "^5.13.2"
mypy = "^1.13.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
