[project]
name = "pinjected-openai"
version = "0.4.21"
description = "openai bindings for pinjected library"
authors = [
    { name = "proboscis", email = "nameissoap@gmail.com" }
]

dependencies = [
    "pinjected",
    "openai",
    "tiktoken",
    "injected-utils",
    "pydub",
    "pillow",
    "loguru",
    "pandas",
    "filelock",
    "reactivex>=4.0.4",
    "moviepy>=1.0.3",
    "pinjected-rate-limit>=0.1.0",
]
readme = "README.md"
requires-python = ">=3.10"

[tool.hatch.metadata]
allow-direct-references = true

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
