[build-system]
requires = [
    "setuptools>=43.0.0",
    "wheel"
]
build-backend = "setuptools.build_meta"

[project]
name = "obz"
description = "Object Shell"
version = "3"
authors = [
    {name = "Bart Thate",email = "bthate@dds.nl"},
]
readme = "README.rst"
license = {text="Public Domain"}
dependencies = [
    "obx",
]
classifiers = [ 
    'Development Status :: 3 - Alpha',
    'License :: Public Domain',
    'Operating System :: Unix',
    'Programming Language :: Python',
    'Topic :: Utilities'
]


[project.scripts]
'obz'  = 'obz.control:wrapped'
'obzd' = 'obz.daemon:main'
'obzs' = 'obz.service:wrapped'


[project.urls]
"home" = "https://pypi.org/project/obz"
"bugs" = "https://github.com/otpcr/obz/issues"
"source" = "https://github.com/otpcr/obz"

[tool.setuptools]
packages = [
    "obz",
    "obz.modules"
]
zip-safe=true
