[tool.poetry]
name = "mysql-api"
version = "0.1.2"
description = "封装mysql操作"
authors = ["LiuWei <183074632@qq.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.8"
sqlalchemy = "^2.0.36"
pymysql = "^1.1.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
