[tool.poetry]
name = "backtester272"
version = "0.2.0"
description = "A sample Python project"
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "^3.10"
pandas = "^2.2.3"
numpy = "1.26.4"
binance = "^0.3"
yfinance = "^0.2.50"
matplotlib = "^3.9.3"
plotly = "^5.24.1"
seaborn = "^0.13.2"
scipy = "^1.14.1"
python-binance = "^1.0.25"


[tool.poetry.dev-dependencies]
pytest = "^6.2.5"