[build-system]
requires = ['setuptools >=61.0']
build-backend = 'setuptools.build_meta'

[project]
name = 'test-dev-toml'
version = '0.0.7'
# additional packages to install
dependencies = [
    # 'dep1',
    # 'dep2',
]
requires-python = '>=3.9'
authors = [{ name = 'J. Arrizza', email = 'cppgent0@gmail.com' }]
maintainers = [
    { name = 'J. Arrizza', email = 'cppgent0@gmail.com' },
]
description = 'test project for toml dev'
readme = { file = 'README.md', content-type = 'text/markdown' }
license = { text = 'MIT' }
keywords = ['setuptools', 'toml', 'generation', 'python']

classifiers = [
    # "Private :: Do Not Upload",   # use to prevent upload
    # Choose either '3 - Alpha', '4 - Beta' or '5 - Production/Stable'
    'Development Status :: 1 - Planning',
    'Environment :: Console',
    'Intended Audience :: Developers',
    'Topic :: Utilities',
    'Programming Language :: Python :: 3.9',
    'License :: OSI Approved :: MIT License',
]

[project.urls]
'Website' = 'https://arrizza.com/test-dev-toml'
'Source' = 'https://bitbucket.org/arrizza-public/test-dev-toml/src/master'
'Download' = 'https://bitbucket.org/arrizza-public/test-dev-toml/get/master.zip'
# 'Bug Reports' = 'TODO https://github.com/pypa/sampleproject/issues'
# 'Funding' = 'TODO https://donate.pypi.org'
# 'Say Thanks!' = 'TODO http://saythanks.io/to/example'

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
where = ['test_dev_toml']
# exclude_package_data={'./test_dev_toml/lib': ['.gitignore']},
exclude = ['.gitignore']

[project.optional-dependencies]
# None
[project.scripts]
# None e.g. spam-cli = "spam:main_cli"

