[build-system]
#requires = ["setuptools>=42", "wheel"]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "dr14meter"
version = "1.1.0rc2"
description = "Compute the dynamic range DR14 value of the given audio files"
keywords = ["dr14", "dynamic range"]
authors = [
    { name = "pe7ro", email = "44572319+pe7ro@users.noreply.github.com " }
]
readme = "README.md"
license = { text = "GPL-3.0+" }
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Environment :: Console",
    "Intended Audience :: End Users/Desktop ",
    "License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)",
    "Operating System :: POSIX :: Linux",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.12",
    "Topic :: Multimedia :: Sound/Audio :: Analysis"
]

dependencies = [
    "numpy",
    'mutagen',
]

#[project.optional-dependencies]
#dev = [
#    "numpy",
#    'mutagen',
#]


[project.urls]
"Homepage" = "https://github.com/pe7ro/p7_dr14tmeter "
"Bug Reports" = "https://github.com/pe7ro/p7_dr14tmeter /issues"
"Source" = "https://github.com/pe7ro/p7_dr14tmeter "

[project.scripts]
dr14meter = "dr14meter:main"

#[tool.setuptools]
#packages = ["dr14tmeter"]
#scripts = ["dr14tmeter"]