[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = 'agi_med_utils'
requires-python = ">= 3.11"

authors = [{ name = 'AGI-MED-TEAM' }]
description = 'Utils for agi-med team'
readme = 'README.md'

dynamic = ['version', 'dependencies']

[tool.setuptools.packages.find]
where = ["src"]


[tool.setuptools.dynamic]
version = { attr = "agi_med_utils.__version__" }
dependencies = { file = ['requirements.txt'] }
