[project]
name = "datasets-dump"
version = "0.1.3"
description = "A tool for dumping datasets from the Hugging Face datasets library"
authors = [{ name = "Jacob Lin", email = "jacoblincool@gmail.com" }]
license = "MIT"
readme = "README.md"
requires-python = ">=3.10"
keywords = ["datasets"]
dependencies = ["datasets>=3.1.0", "tqdm", "Pillow", "soundfile", "numpy"]

[project.urls]
homepage = "https://github.com/JacobLinCool/datasets-dump"
repository = "https://github.com/JacobLinCool/datasets-dump"

[project.scripts]
datasets-dump = "datasets_dump.cli:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.sdist]
include = ["datasets_dump/*.py"]
