[project]
name = "ezorm"
version = "0.1.3"
description = "This library is for people who wanna try interactive with database in an easy way."
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "duckdb>=1.1.3",
    "pandas>=2.2.3",
    "pydantic>=2.10.2",
]
