[project]
name = "psystate"
version = "0.1.0"
description = "Stateful experiments using Psychopy"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "attridict",
    "frozendict",
    "numpy",
    "pandas",
    "psychopy>=2023.1.0",
    "lazy-loader",
    "psyquartz",
]

[project.optional-dependencies]
dev = [
    "pytest",
    "pytest-mock",
    "pytest-cov",
]

[tool.hatch.build.targets.sdist]
exclude = [
    "/examples",
    "/.vscode",
    "/.github",
]
