[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "klabmodels"
version = "0.3.15"
description = "Data models for Kodelab's AI products"
readme = "README.md"
requires-python = ">=3.6"
license = {text = "MIT"}
authors = [
    { name = "Maurizio Santamicone", email = "maurizio@kodelab.io" }
]

dependencies = [
    "pydantic[email]",
    "redis-om", 
    "tiktoken"
]

[project.urls]
"Homepage" = "https://github.com/kodelabio/klabmodels.git"
