[project]
name = "print-wp-sources"
version = "0.2"
authors = [
  { name="Jeffrey Serio", email="hyperreal@fedoraproject.org" },
]
description = "Print sources from Wikipedia articles to stdout."
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)",
    "Operating System :: OS Independent",
]
dependencies = ["beautifulsoup4>=4.12.3"]

[project.scripts]
print-wp-sources = "print_wp_sources:main"

[project.urls]
Homepage = "https://codeberg.org/hyperreal/print-wp-sources"
Issues = "https://codeberg.org/hyperreal/print-wp-sources/issues"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
