[tool.poetry]
name = "gd-st-custom-datatable"
version = "0.2.3"
description = ""
authors = ["Gnomon Digital <contact@gnomondigital.com>"]
readme = "README.md"
packages = [{include = "gdstdatatable"}]
include = [
  { path = "gdstdatatable/frontend/build/**/*", format = ["sdist", "wheel"] }
]

[tool.poetry.dependencies]
python = "^3.10"
streamlit = "^1.40.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
