[project]
name = "RTandCasKinetics"
version = "0.2.0"
description = "Model that investigates the combined kinetics of HIV reverse transcriptase and CRISPR Cas12a."
authors = [
    { name = "Maya Singh", email = "msingh6@uw.edu" },
]
dependencies = [
    "numpy>=1.24.0",
    "matplotlib>=3.9.3",
    "tellurium>=2.2.10",
    "pytest>=8.3.4",
    "pyqt5>=5.15.11",
    "pip>=24.3.1",
]
requires-python = ">=3.9"
readme = "README.md"

[project.license]
text = "MIT"

[project.urls]
Homepage = "https://github.com/msingh0606/RTandCasKinetics"

[build-system]
requires = [
    "pdm-backend",
]
build-backend = "pdm.backend"

[tool.pdm]
distribution = true
