[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "at-common-workflow"
version = "1.0.2"
description = "A robust, asynchronous workflow management system for Python that enables the creation and execution of complex task dependencies using a Directed Acyclic Graph (DAG) approach"
requires-python = ">=3.11"
readme = "README.md"
dependencies = [
    "iniconfig==2.0.0",
    "packaging==24.2",
    "pluggy==1.5.0",
    "pytest==8.3.3",
    "pytest-asyncio==0.24.0",
    "pydantic==2.10.0",
    "pydantic_core==2.27.0",
    "tomli==2.1.0"
]

[project.urls]
"Homepage" = "https://github.com/apex-trader/at-common-workflow"
"Bug Tracker" = "https://github.com/apex-trader/at-common-workflow/issues"