[project]
name = "rich-toolkit"
version = "0.11.1"
description = "Rich toolkit for building command-line applications"
readme = "README.md"
requires-python = ">=3.8"
dependencies = ["rich>=13.7.1", "click>=8.1.7", "typing-extensions>=4.12.2"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.uv]
dev-dependencies = [
    "pytest>=8.3.2",
    "pdbpp>=0.10.3",
    "inline-snapshot>=0.12.1",
    "uvicorn>=0.30.6",
    "fastapi[standard]>=0.112.2",
    "mypy>=1.11.2",
]
