[tool.poetry]
name = "tfrunner"
version = "0.1.0"
description = ""
authors = ["Gilberto Cunha <grncunha13@gmail.com>"]
readme = "README.md"

[tool.poetry.scripts]
tfrunner = "tfrunner.main:cli"

[tool.poetry.dependencies]
python = "^3.12"
typer = "^0.15.0"
requests = "^2.32.3"
pydantic = "^2.10.3"
pyyaml = "^6.0.2"


[tool.poetry.group.test.dependencies]
pytest = "^8.3.4"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
