[tool.poetry]
name = "uhlibs"
version = "0.8.4"
description = "UHIU Python libraries & utilities"
authors = ["Derek Davie <ddavie@unitehere.org>", "Nola Watson <nwatson@unitehere.org>"]
license = "Proprietary"
readme = "README.md"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]


[tool.poetry.dependencies]
python = "^3.10"
prettytable = "^3.11.0"
PyYAML = "^6.0.2"
requests = ">2"
tomli = {markers = "python_version < \"3.11\"", version = "^2.0.2"}
exceptiongroup = "^1.2.2"
civis = "^2.3.0"
flask = "*"
pymongo = "*"
python-odata = "*"
pyodbc = "*"
reportLab = "*"
psycopg = "*"
redit = "*"
azure-keyvault-secrets = "^4.9.0"
azure-identity = "^1.19.0"


[tool.poetry.group.dev.dependencies]
coverage = "^7.6.1"
pytest = "^8.3.3"
pytest-cov = "^5.0.0"
pytest-mock = "^3.14.0"
flake8 = "^7.1.1"
locust = "^2.31.8"
twine = "^5.1.1"


[tool.poetry.group.strike.dependencies]
pyodbc = "^5.1.0"


[tool.poetry.group.odata.dependencies]
python-odata = "^0.5.8"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

