[build-system]
requires = ["setuptools>=69.0"]
build-backend = "setuptools.build_meta"

[project]
name = "tp_but_ge2i"
version = "2025.0.1"
authors = [
  { name="SRD", email="didier.larraillet@srd-energies.fr" },
]
description = 'An educational package for 3rd year BUT GE2I'
readme = {file="README.md", content-type="text/markdown"}
license={text = "MIT License"}
requires-python = ">=3.10"
classifiers = [
    'Development Status :: 3 - Alpha',
    'Intended Audience :: Education',
    'License :: OSI Approved :: MIT License',  
    'Operating System :: OS Independent',        
    'Programming Language :: Python :: 3.10'
]
dependencies = [
	'numpy',
	'pandas>=2.2.0',
	'pandapower>=2.13',
	'tqdm',
	'matplotlib',
    'xlrd>=2.0.1',
	'openpyxl',
    'jupyter'
]

[tool.setuptools]
packages=["tp_but_ge2i","tp_but_ge2i.data", "tp_but_ge2i.src"]
include-package-data=true

[tool.setuptools.package-data]
"tp_but_ge2i"=["*.ipynb"]
"tp_but_ge2i.data"=["*.xlsx","*.docx", "*.pdf"]
"tp_but_ge2i.src"=["*.py"]

[project.urls]
Homepage = "https://test.pypi.org/project/tp-but-ge2i/"