[tool.poetry]
name = "redis_flask"
version = "0.0.2"
description = "Redis extension for Flask app"
authors = ["Robotz213 <nicholas@robotz.dev>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
Flask = "^3.1.0"
redis = "^5.2.0"

[tool.poetry.group.dev.dependencies]
flake8 = "^7.1.1"
isort = "^5.13.2"
black = "^24.10.0"
ruff = "^0.8.1"
pre-commit = "^4.0.0"
mypy = "^1.13.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
