[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"


[tool.setuptools.packages.find]
where = ["src"]


[project]
name = "douglog"
version = "0.2.5"
description = "Simple logging CLI tool"
readme = "README.md"
authors = [
    {name = "Douglas Keller", email = "dg.kllr.jr@gmail.com"},
    ]
license = {file = "LICENSE"}
requires-python = ">=3.12.0"
dependencies = [
    "click",
    "numpy",
    ]


[project.scripts]
dlog = "douglog.douglog:dlog"


[project.urls]
Homepage = "https://github.com/dkllrjr/douglog"
Repository = "https://github.com/dkllrjr/douglog.git"
