[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "skyhook-timer"
version = "0.0.43"
description = "A Skyhook Timer app for Alliance Auth."
readme = "README.md"
authors = [{name = "kjelpw", email = "kjelpw@protonmail.com"}]
license = {file = "LICENSE"}
keywords = ["allianceauth", "eve-online", "skyhook", "timers"]
dependencies = [
    "django>=3.2",
]

[tool.setuptools]
include-package-data = true

[project.urls]
Homepage = "https://github.com/kjelpw/skyhook-app"
Source = "https://github.com/kjelpw/skyhook-app"
