[project]
name = "pyapicaller"
version = "0.1.8"
description = "Easily connect any API to OpenAI function calling"
authors = [{ name="Roman Medvedev", email="pypi@romavm.dev" }]
readme = "README.md"
requires-python = ">=3.9"
license = {text = "MIT"}

keywords = ["API", "caller", "Python"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Topic :: Software Development :: Libraries :: Python Modules",
]
dependencies = [
    'jsonref',
    'pydantic',
    'pyyaml'
    ]

[project.urls]
homepage = "https://github.com/Romamo/pyapicaller"

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"
