[build-system]
requires = [ "poetry-core>=1.0.0",]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "django-silica"
version = "0.1.68"
description = "A reusable Django app for Silica functionalities."
authors = [ "Dyvenia",]
license = "MIT"
readme = "README.md"
classifiers = [ "Development Status :: 3 - Alpha", "Intended Audience :: Developers", "License :: OSI Approved :: MIT License", "Programming Language :: Python :: 3.10", "Framework :: Django",]
keywords = [ "django", "components", "ui", "python",]
[[tool.poetry.packages]]
include = "silica"

[tool.black]
line-length = 88
exclude = "/(\n    \\.git\n  | \\.mypy_cache\n  | \\\\.tox\n  | \\\\.venv\n  | _build\n  | buck-out\n  | build\n  | dist\n  | venv\n)/\n"

[tool.isort]
profile = "black"

[tool.poetry.dependencies]
python = ">=3.8,<4"
shortuuid = "~1.0.11"
beautifulsoup4 = "~4.12.2"
Django = ">=4.2"

[tool.poetry.dev-dependencies]
tblib = "3.0.0"
selenium = "4.24.0"

[tool.poetry.extras]
browser-tests = [ "selenium", "tblib",]
