[project]
name = "irie"
version = "0.0.1"
authors = [
  {name="wd", email="5018-006+wd@users.noreply.github.com"},
  {name="ab",   email="52-93467+ab@users.noreply.github.com"}
]
description="Infrastructure Resilience Engine"

license = {file = ".github/LICENSE.txt"}
readme = "README.md"

keywords = [
  "visualization",
  "rendering",
  "seismic",
  "opensees",
  "post-processing",
  "finite-element-analysis",
  "glTF"
] 

dependencies = [
  "opensees",
  "quakeio",
  "bottle",
  "openbim",
  "Django==5.1.2",
  "asgiref==3.8.1",
  "autopep8",
  "gunicorn==23.0.0",
  "pytz==2021.3",
  "sqlparse==0.5.1",
  "toml>=0.10.2",
  "whitenoise==5.3.0",
  "crispy-bootstrap5 ",
  "django-crispy-forms",
  "django-environ==0.11.2",
  "djangorestframework==3.15.2",
  "djangorestframework-simplejwt==5.3.1",
  "folium",
  "pandas",
  "numpy",
  "orjson",
  "jsonschema",
  "dj-database-url==2.1.0"
]

classifiers = [
    'Development Status :: 4 - Beta',
    'Intended Audience :: Science/Research',
    'Intended Audience :: Developers',
    'License :: OSI Approved :: BSD License',
    'Programming Language :: C',
    'Programming Language :: Python',
    'Programming Language :: Python :: 3',
    'Programming Language :: Python :: 3.7',
    'Programming Language :: Python :: 3.8',
    'Programming Language :: Python :: 3.9',
    'Programming Language :: Python :: 3.10',
    'Programming Language :: Python :: 3.11',
    'Programming Language :: Python :: 3.12',
    'Programming Language :: Python :: 3 :: Only',
    'Topic :: Software Development',
    'Topic :: Scientific/Engineering',
    'Operating System :: Microsoft :: Windows',
    'Operating System :: POSIX',
    'Operating System :: Unix',
    'Operating System :: MacOS',
]


[project.urls]
Repository = "https://github.com/STAIRLab/irie"
Documentation = "https://structures.live"

[project.scripts]
irie = "irie.__main__:main"

[build-system]
requires = [
    "setuptools >= 52.0.2",
]

build-backend = "setuptools.build_meta"

[tool.setuptools.package-data]
irie = ["assets/*"]


