[tool.poetry]
name = "tire-cpd"
version = "0.1.0"
description = "This is an unsupervised change point detection toolbox, including time-invariant representation (TIRE) model with diamond loss, multi-channel time-invariant representation (MC-TIRE) model, and multi-view time-invariant representation (multiview TIRE) model."
authors = ["Zhenxiang Cao"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
numpy = "1.23.5"
pandas = "2.1.1"
scipy = "1.10.1"
tensorflow = "2.12.0"
tensorflow-probability = "0.20.0"
matplotlib = "3.7.4"
seaborn = "0.12.2"
scikit-learn = "1.4.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
