[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "pytest-fixture-forms"
version = "0.2.0"
description = "A pytest plugin for creating fixtures that holds different forms between tests."
readme = "README.md"
authors = [{ name = "eliav2", email = "louski.a@gmail.com" }]
requires-python = ">=3.10"
dependencies = [
    "pytest>=7.0.0,<9.0.0",  # Support both pytest 7 and 8
]
classifiers = [
    "Framework :: Pytest",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12"
]
#[project.peer-dependencies] # wait for pep 735 peer dependencies to be widely supported
#pytest = ">=7.0.0,<9.0.0"  # Support both pytest 7 and 8
[project.urls]
Homepage = "https://github.com/Eliav2/pytest-fixture-forms"

[project.entry-points.pytest11]
fixture_forms = "pytest_fixture_forms.plugin"
[project.optional-dependencies]
dev = [
    "ruff",
    "tox",
    "pytest-xdist"
]

[tool.ruff]
line-length = 120
