[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "python3-cyberfusion-sync-support"
version = "1.3"
description = "Library for syncing objects (e.g. directories)."
readme = "README.md"
authors = [
    { name = "Cyberfusion", email = "support@cyberfusion.io" },
]
dependencies = [
    "cached_property==1.5.2",
    "python3-cyberfusion-common~=2.9",
    "python3-cyberfusion-cluster-support~=2.0",
]

[project.urls]
"Source" = "https://github.com/CyberfusionIO/python3-cyberfusion-sync-support"
