[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "temp4hifu"
version = "0.1.2"
authors = [
  { name="Gerald Lee", email="gerald13@uw.edu" },
]
description = "A Python package designed to estimate the temperature increase due to high intensity focused ultrasound (HIFU) excitation"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dynamic = ["license"]

[project.urls]
Homepage = "https://github.com/C2H5OH-Consumer/temp4hifu"